spring:
  application:
    name: web-shop
  datasource:
    driverClassName: org.postgresql.Driver
    initialization-mode: always
    password: ${PASS}
    platform: postgres
    url: jdbc:postgresql://localhost:5432/web_shop
    username: postgres
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false
jwt:
  secret: security

server:
  port: 9000
#  ssl:
#    key-store: classpath:local-ssl.p12
#    key-store-password: password
#    keyStoreType: PKCS12
#    keyAlias: local_ssl
managment:
  security:
    enabled: true

shop-auth:
  client-id: 123456789
  client-secret: 123


psp:
  url: 'http://localhost:8000'

shop:
  url: 'http://localhost:4200'
